name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: print greeting 
        run: |
          echo "Hello Mohamed"
          echo "Hello Mesbah"
      - name: pring goodbye
        run: echo "Done - bye ! " 
    
