name: NodeJS Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout the code from github
      - name: get code from github
        uses: actions/checkout@v3

      # install nodejs
      - name: install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # install dependencies
      - name: install dependencies
        run: npm install

      # run tests
      - name: run tests
        run: npm test
